export default {
  pages: [
    'pages/index/index',
    'pages/coach/index',
    'pages/coach/detail/index',
    'pages/booking/index',
    'pages/mine/index',
    'pages/login/wechat/index',
    'pages/login/phone/index',
    'pages/login/protocol/index',
    'pages/profile/complete/index',
    'pages/account/cancel/index',
    'pages/settings/index',
    'pages/terms/index',
    'pages/terms/detail/index',
    'pages/privacy/index',
    'pages/package/list/index',
    'pages/package/detail/index',
    'pages/package/custom/index',
    'pages/package/mine/index',
    'pages/package/mine/detail/index',
    'pages/order/confirm/index',
    'pages/order/payment/index',
    'pages/order/detail/index',
    'pages/order/list/index',
    'pages/refund/apply/index',
    'pages/ai-assistant/index',
    'pages/ai-assistant/entry/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'leyoSwimming',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#8C8C8C',
    selectedColor: '#1890FF',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/calicat/icons/tab-index.png',
        selectedIconPath: 'assets/calicat/icons/tab-index-active.png',
      },
      {
        pagePath: 'pages/coach/index',
        text: '教练',
        iconPath: 'assets/calicat/icons/tab-coach.png',
        selectedIconPath: 'assets/calicat/icons/tab-coach-active.png',
      },
      {
        pagePath: 'pages/ai-assistant/entry/index',
        text: 'AI 助理',
        iconPath: 'assets/calicat/icons/tab-ai.png',
        selectedIconPath: 'assets/calicat/icons/tab-ai.png',
      },
      {
        pagePath: 'pages/booking/index',
        text: '预约',
        iconPath: 'assets/calicat/icons/tab-booking.png',
        selectedIconPath: 'assets/calicat/icons/tab-booking-active.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: 'assets/calicat/icons/tab-mine.png',
        selectedIconPath: 'assets/calicat/icons/tab-mine-active.png',
      },
    ],
  },
};
