export default {
  pages: [
    'pages/index/index',
    'pages/coach/index',
    'pages/coach/detail/index',
    'pages/booking/index',
    'pages/mine/index',
    'pages/login/wechat/index',
    'pages/login/phone/index',
    'pages/login/protocol/index',
    'pages/profile/complete/index',
    'pages/account/cancel/index',
    'pages/settings/index',
    'pages/terms/index',
    'pages/terms/detail/index',
    'pages/privacy/index',
    'pages/package/list/index',
    'pages/package/detail/index',
    'pages/package/custom/index',
    'pages/package/mine/index',
    'pages/package/mine/detail/index',
    'pages/order/confirm/index',
    'pages/order/payment/index',
    'pages/order/detail/index',
    'pages/order/list/index',
    'pages/refund/apply/index',
    'pages/ai-assistant/index',
    'pages/ai-assistant/entry/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'leyoSwimming',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#1890ff',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
      },
      {
        pagePath: 'pages/coach/index',
        text: '教练',
      },
      {
        pagePath: 'pages/ai-assistant/entry/index',
        text: 'AI 助理',
      },
      {
        pagePath: 'pages/booking/index',
        text: '预约',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
      },
    ],
  },
};
