-- 最小化占位 schema，后续按 US 需求逐步补充
CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) UNIQUE,
  phone VARCHAR(20) UNIQUE,
  nickname VARCHAR(64),
  avatar_url VARCHAR(512),
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
