#!/usr/bin/env pwsh
#requires -Version 5.1

<#
.SYNOPSIS
    将 upgrade-hook.ps1 注册为 git post-commit hook。
.DESCRIPTION
    在 .git/hooks/post-commit 生成一个 shell 包装脚本，每次 commit 后自动调用 upgrade-hook.ps1。
    默认只输出提醒并等待用户输入服务器 IP；启用 -AutoDeploy 后可通过环境变量 LEYO_UPGRADE_SERVER_IP 全自动部署。
.PARAMETER AutoDeploy
    是否在 post-commit 中启用自动部署（仍需要设置 LEYO_UPGRADE_SERVER_IP 环境变量）。
.PARAMETER HostKeyFingerprint
    服务器 SSH 主机密钥指纹，将写入生成的 hook 并传给 upgrade-hook.ps1 / upgrade-server.ps1。
.PARAMETER AcceptHostKey
    自动接受未知 SSH 主机密钥（不推荐用于生产环境）。
.EXAMPLE
    .\scripts\install-upgrade-hook.ps1
    安装默认的交互式提醒 hook。
.EXAMPLE
    .\scripts\install-upgrade-hook.ps1 -AutoDeploy
    安装自动部署 hook（需提前设置环境变量 LEYO_UPGRADE_SERVER_IP）。
.EXAMPLE
    .\scripts\install-upgrade-hook.ps1 -AutoDeploy -HostKeyFingerprint 'SHA256:xxxxx'
    安装自动部署 hook 并固定服务器主机密钥指纹。
#>

[CmdletBinding()]
param(
    [switch]$AutoDeploy,

    [string]$HostKeyFingerprint = "",

    [switch]$AcceptHostKey,

    [string]$ProjectRoot = "$PSScriptRoot\.."
)

$ErrorActionPreference = "Stop"

$gitDir = Join-Path $ProjectRoot ".git"
$hooksDir = Join-Path $gitDir "hooks"
$hookFile = Join-Path $hooksDir "post-commit"
$upgradeHook = Join-Path $ProjectRoot "scripts\upgrade-hook.ps1"

if (-not (Test-Path $gitDir)) {
    throw "未找到 .git 目录，请确认当前是 git 仓库根目录。"
}
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}
if (-not (Test-Path $upgradeHook)) {
    throw "升级触发器脚本不存在：$upgradeHook"
}

# 备份已有的 post-commit hook
if (Test-Path $hookFile) {
    $backup = "$hookFile.backup.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Write-Host "备份已有 hook 到：$backup" -ForegroundColor Yellow
    Copy-Item -Path $hookFile -Destination $backup -Force
}

# shell 路径使用正斜杠，并做单引号转义
$upgradeHookUnix = ($upgradeHook -replace "\\", "/")
$upgradeHookLit = "'" + ($upgradeHookUnix -replace "'", "'\''") + "'"

$autoDeployFlag = if ($AutoDeploy) { "-AutoDeploy" } else { "" }
$hostKeyFlag = ""
if ($HostKeyFingerprint) {
    $escapedFingerprint = $HostKeyFingerprint -replace "'", "'\''"
    $hostKeyFlag = "-HostKeyFingerprint '$escapedFingerprint'"
}
elseif ($AcceptHostKey) {
    $hostKeyFlag = "-AcceptHostKey"
}

$hookContent = "#!/bin/sh
# Auto-generated by scripts/install-upgrade-hook.ps1
# leyoSwimming post-commit upgrade hook

if [ ! -f $upgradeHookLit ]; then
    echo '[leyoSwimming] 升级触发器脚本不存在，跳过。'
    exit 0
fi

if command -v pwsh >/dev/null 2>&1; then
    pwsh -File $upgradeHookLit $autoDeployFlag $hostKeyFlag
elif command -v powershell >/dev/null 2>&1; then
    powershell -File $upgradeHookLit $autoDeployFlag $hostKeyFlag
else
    echo '[leyoSwimming] 未找到 pwsh/powershell，跳过自动升级检查。'
    exit 0
fi
"

# 写入无 BOM 的 LF 换行 Unix shell 脚本，避免 shebang 解析失败
$unixContent = ($hookContent -replace "`r`n", "`n")
[System.IO.File]::WriteAllText($hookFile, $unixContent, [System.Text.UTF8Encoding]::new($false))

# 尝试设置可执行权限（在 Windows Git Bash / WSL / Linux / macOS 下有效）
try {
    $chmod = Get-Command chmod -ErrorAction SilentlyContinue
    if ($chmod) {
        & chmod +x $hookFile
    }
}
catch {
    Write-Warning "无法设置 hook 可执行权限：$_"
}

Write-Host "`npost-commit hook 已安装：$hookFile" -ForegroundColor Green

if ($AutoDeploy) {
    Write-Host "模式：自动部署" -ForegroundColor Cyan
    Write-Host "警告：启用自动部署后，每次 commit 在同时设置 LEYO_UPGRADE_SERVER_IP 与 LEYO_UPGRADE_AUTO_DEPLOY=1 时才会直接部署。" -ForegroundColor Red
    Write-Host "       请确保只在受信任的主分支/稳定环境上启用，并设置环境变量：" -ForegroundColor Red
    Write-Host "  `$env:LEYO_UPGRADE_SERVER_IP = '123.45.67.89'" -ForegroundColor White
    Write-Host "  `$env:LEYO_UPGRADE_AUTO_DEPLOY = '1'" -ForegroundColor White
    if (-not $HostKeyFingerprint -and -not $AcceptHostKey) {
        Write-Host "       同时建议设置主机密钥环境变量以避免每次询问：" -ForegroundColor Yellow
        Write-Host "  `$env:LEYO_UPGRADE_HOST_KEY = 'SHA256:xxxxx'" -ForegroundColor White
    }
}
else {
    Write-Host "模式：交互式提醒（commit 后会提示输入服务器 IP 并确认升级）" -ForegroundColor Cyan
}

Write-Host "`n如需卸载，删除 $hookFile 即可。" -ForegroundColor Gray
